### ISSUE TITLE
DNS Resolution

### ISSUE THREAD

**Issue by gabrielwpulido** [NerdOfLinux/Scripts#1]
Hi Nerd Of Linux, awesome script. I've tried to set up this config to resolv my local dns through Openvpn but I can't.

**Comment by NerdOfLinux** [comment]
Please post the output of 

```shell
cat /etc/resolv.conf
```

**Comment by gabrielwpulido** [comment]
I'm connected from my wifi router.

```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 192.168.16.1
nameserver 127.0.1.1
```
Also installed on my server resolvconf and edited the base file with the parameters from my openvpn servers (master & slave). So it can't resolve

**Comment by NerdOfLinux** [comment]
The problem appears to be the fact that the resolvers are within an internal IP address range. So(from what I understand about OpenVPN), the client attempts to use the DNS server with the IP `192.168.16.1` or `127.0.1.1` which will fail because that very likely does not exist outside of the network your server is situated in. The best advice I have is to select a different option, or setup a DNS server on your OpenVPN server, and manually set the DNS to `10.8.0.1` in `/etc/openvpn/server.conf`. To do this, edit the file with:
```shell
sudo nano /etc/openvpn/server.conf
```
and change the lines that look like(according to `resolv.conf`):
```shell
push "dhcp-option DNS 192.168.16.1"
push "dhcp-option DNS 127.0.1.1"
```
to
```shell
push "dhcp-option DNS 10.8.0.1"
```
This *should* work, but I've never had the time to set up my own DNS server. <a href="https://help.ubuntu.com/community/Dnsmasq" target="_blank"> This Ubuntu Wiki</a> post should help you get started.

**Comment by gabrielwpulido** [comment]
Ok. I've stablished connection with openvpn and resolve, but via terminal with openvpn --config user.ovpn, but with network app (plasma-nm) I can't... Maybe some permissions to write /etc/resolv.conf file??

**Comment by gabrielwpulido** [comment]
It solved everything... Thank U man
`sudo dpkg-reconfigure resolvconf`
